[platformio]
src_dir = .
default_envs = waveshare_esp32s3_shogun
core_dir = .pio

[env:waveshare_esp32s3_shogun]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1

monitor_speed = 115200

lib_ldf_mode = chain
lib_compat_mode = off

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_src_filter =
    +<src/*.cpp>

lib_deps =
    4-20ma/ModbusMaster @ ^2.0.1
    knolleary/PubSubClient @ ^2.8

build_flags =
    -I src/

[env:waveshare_esp32s3_shogun_ota]
extends = env:waveshare_esp32s3_shogun
upload_protocol = espota
upload_flags = --auth=${sysenv.OTA_PASSWORD}
